apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: data-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: data-services
  labels:
    app: elasticsearch
    tier: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        tier: search
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: busybox:1.35
          command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: discovery.type
              value: 'single-node'
            - name: ELASTIC_PASSWORD
              value: 'mfAXVOgm'
            - name: ES_JAVA_OPTS
              value: '-Xms128m -Xmx2g'
            - name: xpack.security.enabled
              value: 'true'
            - name: xpack.security.http.ssl.enabled 
              value: 'false'
            - name: xpack.license.self_generated.type
              value: 'trial'
            - name: xpack.ml.use_auto_machine_memory_percent
              value: 'true'
            - name: xpack.security.enrollment.enabled
              value: 'false'
            - name: cluster.routing.allocation.disk.watermark.low
              value: '1g'
            - name: cluster.routing.allocation.disk.watermark.high
              value: '1g'
            - name: cluster.routing.allocation.disk.watermark.flood_stage
              value: '1g'
            - name: bootstrap.memory_lock
              value: 'false'
            - name: network.host
              value: '0.0.0.0'
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          livenessProbe:
            command:
              - sh
              - -c
              - >
                curl --output /dev/null --silent --head --fail -u elastic:mfAXVOgm http://elasticsearch:9200 
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
      nodeSelector:
        cluster-type: data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: data-services
  labels:
    app: elasticsearch
  annotations:
    cloud.google.com/load-balancer-type: 'Internal'
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http
    - port: 9300
      targetPort: 9300
      name: transport
  type: LoadBalancer
