apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-management-service
  namespace: app-services
  labels:
    app: booking-management-service
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-management-service
  template:
    metadata:
      labels:
        app: booking-management-service
        tier: application
    spec:
      serviceAccountName: booking-service-account
      containers:
        - name: booking-management-service
          image: us-east1-docker.pkg.dev/ticket-booking-471523/ticket-booking-repo/booking-management-service:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: 'production'
            - name: DB_HOST
              value: 'data-cluster-postgres'
            - name: DB_PORT
              value: '5432'
            - name: DB_USERNAME
              value: 'postgres'
            - name: DB_PASSWORD
              value: 'password'
            - name: DB_NAME
              value: 'ticket_booking'
            - name: REDIS_HOST
              value: 'data-cluster-redis-write'
            - name: REDIS_PORT
              value: '6379'
            # PubSub Configuration
            - name: GOOGLE_CLOUD_PROJECT
              value: 'ticket-booking-471523'
            - name: PUBSUB_TOPIC
              value: 'reservation-confirmed'
            - name: USE_PUBSUB
              value: 'true'
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /api/booking/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/booking/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      nodeSelector:
        cluster-type: apps
---
apiVersion: v1
kind: Service
metadata:
  name: booking-management-service
  namespace: app-services
  labels:
    app: booking-management-service
spec:
  selector:
    app: booking-management-service
  ports:
    - port: 3001
      targetPort: 3000
      name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: booking-management-service-hpa
  namespace: app-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-management-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
