FROM node:20.19.5-alpine3.22
WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY tsconfig.build.json ./
RUN npm install
RUN npm install @nestjs/cli typescript -g
RUN npm run build
EXPOSE 3000